api:
  base-path: /api
  controllers:
    stats: /stats
    clients: /clients
    drivers: /drivers
    tasks: /tasks
    vehicles: /vehicles
    assignments: /assignments
    legs: /legs
spring:
  config:
    import: secrets.yml
  application:
    name: fleems
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: sqlserver
      mode: always