spring:
  datasource:
    url: jdbc:sqlserver://allsvenskanstats-sql-server.database.windows.net:1433;database=allsvenskanstats-db;user=allsvenskanadmin@allsvenskanstats-sql-server;password=0SeJXmHMj0Xb14;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30